version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly" 
    commit-message:
      prefix: "deps"
      include: "scope"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all" 
